const db =[
	{
		id: 1,
		name: "Golden Moneyplant",
		description: "Money plant is an excellent indoor plant due to its ability ot survive in low light . It is an Air Purifier plant as it efficiently removes indoor pollutants. It is also an easy to care for plant suitable in living room, balcony, bedroom or in hanging baskets. \n This plant with its beautiful golden heart shaped leaves is believed to bring good luck & prosperity to your home according to Feng Shui. \n Watering requirement for the plant is generally twice a week. But it is ideal to water it whenever the top layer of the soil feels dry.",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/61w0c0qeqXL._SL1500_.jpg" ,
        mrp: 395,
		price: 299,
		storeName: "Amazon",
		link: "https://www.amazon.in/dp/B07SWRC12Q",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Air Purifier"],
		isNew: 0
	},
	{
		id: 2,
		name: "Hahnii Snake Plant",
		description: "Air Purifier Plant. \n This plant is low on maintenance and is often seen in corridors and corners of the living room\n Watering Schedule - once a week\n Plant height - 6 to 12 inch; Natural Plant with 4 inches to 5 inches Diameter Pot\n A little bit of color shade may vary as these are live plants",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/61FBpTSRfLL._SX679_.jpg" ,
        mrp: 495,
		price: 399,
		storeName: "Amazon",
		link: "https://www.amazon.in/dp/B071NMHPSY",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Air Purifier"],
		isNew: 0
	},
	{
		id: 3,
		name: "Nature Live Plant",
		description: "Aglaonema Red is also one of the most stylish houseplant and needs minimal care and can thrive extremely well in low light levels.\n With its colorful foliage this plant is a perfect home-decor plant.\n Watering requirement for the plant is generally twice a week. But it is ideal to water it whenever the top layer of the soil feels dry.\n Plant height without the pot is - 6 to 11 inch. And the plant spread is ranging between - 8 to 12 inch. And the Pot height is 4 inch.",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/71XnBPcAW7L._SL1500_.jpg" ,
        mrp: 395,
		price: 299,
		storeName: "Amazon",
		link: "https://www.amazon.in/dp/B07SRGBKVB",
		inStock: false,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Home Decor"],
		isNew: 0
	},
	{
		id: 4,
		name: "Lucky Bamboo Plant",
		description: "Images shown are of the 12 months old plant - Actual Size may defer. \nIt is a natural plant. \nIt is a Feng Shui Gift. \nLucky Bamboo a symbol of luck and prosperity making it a common gift and the perfect small house plant.. \nMATERIAL: Natural Plants & Glass Pot. \nPLANT COLOR: Green. \nPOT COLOR: Transparent",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/71ElgO40I0L._SL1500_.jpg" ,
        mrp: 399,
		price: 199,
		storeName: "Amazon",
		link: "https://www.amazon.in/Zaavic-Layer-Lucky-Bamboo-Colored/dp/B0773VTMLX/",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Air Purifier"],
		isNew: 0
	},
	{
		id: 5,
		name: "Groot Flower Pots 3pc",
		description: "Baby Tree Flower Pot with hole, can be also used as pen container, flowerpot. Perfect decoration for your desk or office. \n Commodity material: ABS ( ABS is high quality than PVC ). \n Height about 12 cm. \n Best Decoration Gift. \n Package include : 3 x Baby Tree Flower Pot",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/717XgqyegpL._SL1000_.jpg" ,
        mrp: 899,
		price: 365,
		storeName: "Amazon",
		link: "https://www.amazon.in/Quace-Groot-Flower-Pot/dp/B07WRLD7TF",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Pot"],
		isNew: 0
	},
	{
		id: 6,
		name: "8PCs Plastic Pots",
		description: "Material: Plastic, Colour: Colourful Set. \n Item Dimension: 15 cm x 15 cm x 13 cm. \n Package Contents:8 Pots & 8 Bottom Plate. \n Garden plant pot made of plastic material, light weight and reusable and this nursery pots can be used with various types of soil",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/61uO%2BHVENHL._SL1280_.jpg" ,
        mrp: 582,
		price: 582,
		storeName: "Amazon",
		link: "https://www.amazon.in/Kraft-Seeds-Seedlings-Colourful-Container/dp/B086K9WX2J/",
		inStock: false,
		fastDelivery: true,
		ratings: 3.5,
		categories: ["Pot"],
		isNew: 1
	},
	{
		id: 7,
		name: "Guava Plant",
		description: "The plants are attractive and produce deliciously rich, sweet fruits that are excellent fresh or in desserts. \n Guava botanically known as Psidium guajava, is an evergreen shrub or small tree in the family Myrtaceae grown for its edible fruits. It is the fourth most important fruit in area and production after mango, banana and citrus.\n Being hardy, it gives an assured crop even with little care, and is good for rainfed areas also. Successful Guava cultivation is grown under tropical and sub-tropical climate. In areas with distinct winter season, the yield tends to increase and quality improves.",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-guava-tree-amrud-psidium-guajava-sardar-l49-grown-through-seeds-plant-16968910831756_600x600.jpg" ,
        mrp: 549,
		price: 535,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/guava-tree-amrud-psidium-guajava-sardar-l49-grown-through-seeds-plant",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 8,
		name: "Fig/Anjeer Plant",
		description: "Growing Anjeer plant is an easy way to add a tropical flair to your garden. When you know that its important and how to care for Anjeer plants, you will be rewarded with many years of lovely fruit. The bark is a smooth, silvery gray. The leaves of the tree are the identifying feature, they are about 4 inches long and have 3 or 5 lobes.The species name carica means having papaya-like leaves. The fruit, which is called anjeer, may be top-shaped, or pear-shaped, 1 to 4 in long, and varies in color from yellowish-green to coppery, bronze, or dark-purple.Well loved for their sweet, mild flavor fruit and multiple uses and fig are great source of calcium.	",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-fig-tree-anjeer-fruit-common-fig-fruit-plant-16968860139660_600x600.jpg" ,
        mrp: 399,
		price: 399,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/fig-tree-anjeer-fruit-common-fig-fruit-plant",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 9,
		name: "Banana/Kela Plant",
		description: "Growing Banana plant is an easy way to add a tropical flair to your garden. When you know that it has a unique leaf shape, edible fruits and how to care for Banana plants, you will be rewarded with many years of edible fruits.  This product does not have the flowers and fruits at the time of shipping. After, 9-10 months, the plant will bloom and have beautiful fruits. Banana is the fruit of a plant of the genus Musa and Musaceae family, which is cultivated primarily for food and secondarily for the production of fibre used in the textile industry are also cultivated for ornamental purposes.The banana is an edible fruit, botanically a berry, produced by several kinds of large herbaceous flowering plants.",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-banana-g9-kela-plant-16968612446348_600x600.jpg" ,
        mrp: 449,
		price: 449,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/banana-g9-kela-plant",
		inStock: true,
		fastDelivery: false,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 10,
		name: "Lemon/Nimboo Plant",
		description: "Kagzi Lime is popular for its beautiful appearance and pleasing flavour and for its excellent food qualities. \n Kagzi Nimboo (Citrus aurantifolia) is a perennial evergreen tree belongs to family Rutaceae. The stem is irregularly slender branched and possesses short and stiff sharp spines or thorns 1 cm or less. Leaves are alternate, elliptical to oval. \n Lime is popular for its beautiful appearance and pleasing flavor and for its excellent food qualities.",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-kagzi-nimboo-lemon-tree-plant-16968973811852_600x600.jpg" ,
        mrp: 499,
		price: 499,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/kagzi-nimboo-lemon-tree-plant",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 11,
		name: "Golden Coconut",
		description: "If you have access to a fresh coconut, you might think that it would be fun to grow a coconut plant, and you would be right.Growing a coconut palm tree is easy and fun. \n Below you will find the steps for planting coconuts and growing coconut palms from them.Easily grown in average, medium moisture, well-drained soils in full sun. Prefers fertile, slightly alkaline, loose, somewhat gritty loams with good drainage. \n Add lime to acidic soils to adjust the soil pH. Best grown with regular and consistent moisture during the growing season.",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-nariyal-coconut-tree-golden-hybrid-plant_600x600.jpg" ,
        mrp: 699,
		price: 699,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/nariyal-coconut-tree-golden-hybrid-plant",
		inStock: true,
		fastDelivery: false,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 12,
		name: "6PCs Planters",
		description: "Designed to bring color and vibrancy to your home/office interiors. It makes growing plants more fun. \n These pots introduce new designs with latest color trends keeping in mind the increasing demand for planters for garden, terrace, indoor and outdoor plants.The opinion of customers, plant nurseries, architects, and professionals has been taken into consideration while selecting this range of pots. \n This pot has sufficient drainage holes at the bottom, which helps to avoid the overwatering to the plant.",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-planters-3-1-inch-8-cm-square-plastic-planter-with-rounded-edges-blue-16968456831116_600x600.jpg" ,
        mrp: 354,
		price: 282,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/blue-color-planters/products/3-1-inch-square-plastic-planter-with-rounded-edges-blue",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Pot"],
		isNew: 1
	},
]
module.exports = db;