
export const productsDB = [
	{
		id: 1,
		name: "Golden Moneyplant",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/61w0c0qeqXL._SL1500_.jpg" ,
        mrp: 395,
		price: 299,
		storeName: "Amazon",
		link: "https://www.amazon.in/dp/B07SWRC12Q",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Air Purifier"],
		isNew: 0
	},
	{
		id: 2,
		name: "Hahnii Snake Plant",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/61FBpTSRfLL._SX679_.jpg" ,
        mrp: 495,
		price: 399,
		storeName: "Amazon",
		link: "https://www.amazon.in/dp/B071NMHPSY",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Air Purifier"],
		isNew: 0
	},
	{
		id: 3,
		name: "Nature Live Plant",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/71XnBPcAW7L._SL1500_.jpg" ,
        mrp: 395,
		price: 299,
		storeName: "Amazon",
		link: "https://www.amazon.in/dp/B07SRGBKVB",
		inStock: false,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Home Decor"],
		isNew: 0
	},
	{
		id: 4,
		name: "Lucky Bamboo Plant",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/71ElgO40I0L._SL1500_.jpg" ,
        mrp: 399,
		price: 199,
		storeName: "Amazon",
		link: "https://www.amazon.in/Zaavic-Layer-Lucky-Bamboo-Colored/dp/B0773VTMLX/",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Indoor Plant","Air Purifier"],
		isNew: 0
	},
	{
		id: 5,
		name: "Groot Flower Pot",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/717XgqyegpL._SL1000_.jpg" ,
        mrp: 899,
		price: 365,
		storeName: "Amazon",
		link: "https://www.amazon.in/Quace-Groot-Flower-Pot/dp/B07WRLD7TF",
		inStock: true,
		fastDelivery: true,
		ratings: 4,
		categories: ["Pot"],
		isNew: 0
	},
	{
		id: 6,
		name: "8PCs Plastic Pots",
		imageUrl: "https://images-na.ssl-images-amazon.com/images/I/61uO%2BHVENHL._SL1280_.jpg" ,
        mrp: 582,
		price: 582,
		storeName: "Amazon",
		link: "https://www.amazon.in/Kraft-Seeds-Seedlings-Colourful-Container/dp/B086K9WX2J/",
		inStock: false,
		fastDelivery: true,
		ratings: 3.5,
		categories: ["Pot"],
		isNew: 1
	},
	{
		id: 7,
		name: "Guava Plant",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-guava-tree-amrud-psidium-guajava-sardar-l49-grown-through-seeds-plant-16968910831756_600x600.jpg" ,
        mrp: 549,
		price: 535,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/guava-tree-amrud-psidium-guajava-sardar-l49-grown-through-seeds-plant",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 8,
		name: "Fig/Anjeer Plant",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-fig-tree-anjeer-fruit-common-fig-fruit-plant-16968860139660_600x600.jpg" ,
        mrp: 399,
		price: 399,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/fig-tree-anjeer-fruit-common-fig-fruit-plant",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 9,
		name: "Banana/Kela Plant",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-banana-g9-kela-plant-16968612446348_600x600.jpg" ,
        mrp: 449,
		price: 449,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/banana-g9-kela-plant",
		inStock: true,
		fastDelivery: false,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 10,
		name: "Lemon/Nimboo Plant",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-plants-kagzi-nimboo-lemon-tree-plant-16968973811852_600x600.jpg" ,
        mrp: 499,
		price: 499,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/kagzi-nimboo-lemon-tree-plant",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 11,
		name: "Golden Coconut",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-nariyal-coconut-tree-golden-hybrid-plant_600x600.jpg" ,
        mrp: 699,
		price: 699,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/fruit-plants/products/nariyal-coconut-tree-golden-hybrid-plant",
		inStock: true,
		fastDelivery: false,
		ratings: 5,
		categories: ["Fruit Plant"],
		isNew: 1
	},
	{
		id: 12,
		name: "6PCs Planters",
		imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-planters-3-1-inch-8-cm-square-plastic-planter-with-rounded-edges-blue-16968456831116_600x600.jpg" ,
        mrp: 354,
		price: 282,
		storeName: "NurseryLive",
		link: "https://nurserylive.com/collections/blue-color-planters/products/3-1-inch-square-plastic-planter-with-rounded-edges-blue",
		inStock: true,
		fastDelivery: true,
		ratings: 5,
		categories: ["Pot"],
		isNew: 1
	},
];

export const productCategories = ["Fruit Plant","Flower Plant","Indoor Plant","Air Purifier","Home Decor","Tool","Pot"];
